image: php:8.1

variables:
  SYMFONY_VERSION: 5

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

build:
  stage: build
  script:
    - echo "Build started"

test:
  stage: test
  script:
    - echo "Running tests"
    - php bin/phpunit

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - git pull && rm -rf var/cache && php bin/console c:c